### ISSUE TITLE
na.rm() does not properly overwrite objects only within its containing functions

### ISSUE THREAD

**Issue by katzfuss** [katzfuss-group/GPvecchia#20]
The code can now, in principle, handle NAs in observations z. However, the scoping/assigning done by na.rm() does not work properly. It should overwrite z and other objects, but only within the function that calls na.rm() (e.g., vecchia_likelihood()), not in the global environment. Here is some example code:

```
covparms=c(1,2,.5); nuggets=.2
z=1:5; locs=matrix(1:5,ncol=1); z[5]=NA

vecchia.approx=vecchia_specify(locs,m=2)

## this does not work!!
# vecchia_likelihood(z,vecchia.approx,covparms,nuggets)

# running the code inside vecchia_likelihood directly does work
U.obj=createU(vecchia.approx,covparms,nuggets,covmodel)
na.rm()
vecchia_likelihood_U(z,U.obj)

# gives the same answer as when removing the NA obs completely
z=z[1:4]; locs=locs[1:4,,drop=FALSE]
vecchia.approx=vecchia_specify(locs,m=2)
vecchia_likelihood(z,vecchia.approx,covparms,nuggets)
```

**Comment by marcinjurek** [comment]
Dr. Katzfuss, I'm not sure if I understand the problem here. Also, I tried running the code but I wasn't able to. Do you think I could come by your office today after lunch to discuss it?

**Comment by marcinjurek** [comment]
It seems to me that changing the definition of `na.rm()` to the following one should fix the problem. It did for me but please let me know if it worked for you as well. 

```{R}
na.rm=function(){ # overwrites z and U.obj
  p = parent.frame()
  if(any(is.na(z))){
    ind.na=(((1:nrow(p$U.obj$U))[!p$U.obj$latent])[p$U.obj$ord.z])[is.na(p$z)]
    if(any(apply(p$U.obj$U[,ind.na,drop=FALSE],2,nnzero)>2)) stop(
      'NA data is conditioned upon')
    p$U.obj$U = p$U.obj$U[-ind.na,-ind.na]
    p$U.obj$latent = p$U.obj$latent[-ind.na]
    p$U.obj$ord.z = order(order(p$U.obj$ord.z[p$U.obj$ord.z %in% which(!is.na(p$z))]))
    p$z = p$z[!is.na(p$z)]
  }
}
```

**Comment by katzfuss** [comment]
Looks good. Please push. 
@dzilber Please check if this fixes your issue with prediction.

**Comment by marcinjurek** [comment]
pushed

**Comment by dzilber** [comment]
@marcinjurek , can you try running this code without having a variable "z" in the global environment?  
I did a pull and when I remove z using `rm(z)` and call my functions, I still get an error of   `Error in na.rm() : object 'z' not found`.

From what I had read online, the command `<<-` does something nearly identical to `parent.frame()`, and both should work as we want, but for some reason don't.  Perhaps the best way to modify the code is to simplify the operation to two lines instead of making one method do two things.  Or maybe return a list to keep it as one modular code.

```
# remove NAs in data and U 
U.obj =   na.rm(z, U.obj)
z = z[!is.na(z)]
```

**Comment by dzilber** [comment]
Issue resolved.
