### ISSUE TITLE
MRA:  NNarray loses prediction locations

### ISSUE THREAD

**Issue by dzilber** [katzfuss-group/GPvecchia#39]
The code shown below fails with `Error in revNNarray[k, ] : subscript out of bounds`.    The issue may be caused by a bug in   `knt.tree = knot.tree(locs, mra.params)`, since a full set of locations = (locs, pred.locs) goes in but only the observed locs come out.  

@marcinjurek , any ideas?  Can you reproduce the problem?

```
n=10; n.p=10; m=5
# 2-D case
locs <- cbind(runif(n),runif(n))
grid.oneside=seq(0,1,length=sqrt(n.p))
locs.pred=as.matrix(expand.grid(grid.oneside,grid.oneside)) # grid of pred.locs
vecchia.approx1=vecchia_specify(locs,m,ordering = "maxmin",cond.yz =  "SGV",
                                locs.pred, ordering.pred = "obspred",
                               pred.cond = "general",  conditioning = "mra")
```

**Comment by marcinjurek** [comment]
Okay, so right now here is the error I'm getting (thrown by `order_maxmin_exact_obs_pred`).

```{bash}
Error in .C("get_KNN_kd", t(data), as.integer(k), d, n, nn.index = integer(n *  : 
  "get_KNN_kd" not resolved from current namespace (FNN)
```

Specifically, it is thrown by line 425 in `ordering_functions.R`.

I made sure to pull from the remote before running it to work with the most up-to-date version of your code. Just making sure that maybe there are some changes on your end you didn't push. It's not clear to me why the error I'm getting is being thrown.

**Comment by dzilber** [comment]
I do not have any significant changes to push.  Try restarting the workspace; your code should be working without the prediction locations.

**Comment by joeguinness** [comment]
I get this error from time to time. There is some minor bug in how the FNN
package is set up. I've tried to fix this myself but couldn't make any
progress. Usually restarting the R session works for me.

**Comment by dzilber** [comment]
@marcinjurek was correct, I forgot to commit a change to the code.  The error message is misleading.  Fixing this ticket should now be super quick ;)

**Comment by marcinjurek** [comment]
Well, unfortunately, I still can't get rid of this FNN error. Restarting R or R studio didn't help, updating FNN didn't help either. What's worse, if you look at the front page of this document, it seems like there are some known C++ related issues that no one wants to take care of. I would be happy to investigate it but it might be a major time investment.

**Comment by katzfuss** [comment]
The front page of which document?
I thought we had been using the FNN package for a long time, and I was not aware that it was causing any errors.

**Comment by marcinjurek** [comment]
https://cran.r-project.org/web/packages/FNN/FNN.pdf

This is the document. The field `X-CRAN-Comment` suggests there are some issues with C++, although there is no knowing if that's what I come across.

**Comment by joeguinness** [comment]
This error comes up in GpGp intermittently, and I don't fully understand
it. Maybe try removing "library(FNN)" from the first line of NN_kdtree.R?

**Comment by marcinjurek** [comment]
that helped! thanks @joeguinness!

**Comment by marcinjurek** [comment]
@dzilber try the code now. I think I might have fixed it in d4a2fe2.
